all:
  hosts:
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
    wintel0:
      ansible_host: 192.168.1.121
    wintel1:
      ansible_host: 192.168.1.142
    ybox-vm:
      ansible_host: 192.168.1.128